// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/28/2026, 4:35:46 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/juliendeprez/Dev/Projets/nursy-landing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juliendeprez/Dev/Projets/nursy-landing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juliendeprez/Dev/Projets/nursy-landing/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juliendeprez/Dev/Projets/nursy-landing/plugins/**/*.{js,ts,mjs}","/Users/juliendeprez/Dev/Projets/nursy-landing/composables/**/*.{js,ts,mjs}","/Users/juliendeprez/Dev/Projets/nursy-landing/utils/**/*.{js,ts,mjs}","/Users/juliendeprez/Dev/Projets/nursy-landing/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juliendeprez/Dev/Projets/nursy-landing/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/juliendeprez/Dev/Projets/nursy-landing/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/juliendeprez/Dev/Projets/nursy-landing/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;